### ISSUE TITLE
Font styles are not exported properly

### ISSUE THREAD

**Issue by DmitryBaranovskiy** [adobe-research/svgObjectModelGenerator#161]
In OM information about font looks like this:
```json
"textStyle": {
    "fontName": "Source Sans Pro",
    "fontStyleName": "ExtraLight",
    "size": 111,
    "fontPostScriptName": "SourceSansPro-ExtraLight",
    "autoLeading": false,
    "altligature": true,
    "fractions": true,
    "stylisticAlternates": true,
    "baselineDirection": "withStream",
    "textLanguage": "russianLanguage",
    "japaneseAlternate": "defaultForm",
    "contextualLigatures": true,
    "digitSet": "arabicDigits",
    "markYDistFromBaseline": 0,
    "leading": 111,
    "tracking": 5
}
```
The only information about `font-weight` is `fontStyleName`. Currently both Ai and svgOMG put `fontPostScriptName` into CSS, but it doesn’t work in IE or Firefox.

I.E. Current output:
```css
blah {
    font-family: "SourceSansPro-ExtraLight";
}
```
Expected output:
```css
blah {
    font-family: "Source Sans Pro";
    font-weight: 200;
}
```
