### ISSUE TITLE
CSS optimisation duplicates data

### ISSUE THREAD

**Issue by DmitryBaranovskiy** [adobe-research/svgObjectModelGenerator#162]
Example is in [text-styling.svg](https://github.com/adobe-research/svgObjectModelGenerator/blob/master/tests/data/text-styling.svg?short_path=126f0f8):
```css
      .cls-3, .cls-4, .cls-6, .cls-8, .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        font-size: 60px;
      }

      .cls-4, .cls-6, .cls-8, .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        fill: #030303;
        font-size: 60px;
      }

      .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        fill: #030303;
        font-size: 60px;
        font-family: "Arial";
      }
```
Should be
```css
      .cls-3, .cls-4, .cls-6, .cls-8, .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        font-size: 60px;
      }

      .cls-4, .cls-6, .cls-8, .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        fill: #030303;
      }

      .cls-10, .cls-12, .cls-14, .cls-16, .cls-18 {
        font-family: Arial;
      }
```
